### ISSUE TITLE
WebRTC Multiparty

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#106]
This issue is to discuss WebRTC Multiparty support by the Runtime.

We should distinguish two topologies:

* full meshed topology where all peers have peer connections established among them. Should be limited to a small number of peers since it spends lots of bandwidth. This would imply to have a connection data object per pair of peers. This could be handled by a single Multiparty Connector Hyperty or by a Orchestrator Hyperty controlling simpler Two Party Connectors

* Start topology.

**Comment by jboulmal** [comment]
Hello,
here some points to be taking into account:
## Mesh Topology : 
In full mesh WebRTC conference, every peer establishes a connection with the rest of the participant peers. Thus, n*(n-1) number of connections are needed, where `n` is the number of participant peers. For examples, a full mesh topology of 4 users has 12 connections.

In this topology, This topology works well for small number for participants. Indeed, no server is needed Easy to deploy without extra resources. However, it is inefficient for multiparty systems. As the number of participants increases, bandwidth and CPU processing consumption becomes more excessive on client side, which is not scalable, especially for mobile clients.
![untitled diagram 6](https://cloud.githubusercontent.com/assets/15377466/17848940/924c64de-6856-11e6-88e0-dc1b88f106d1.png)

## Star Topology :
Alternatively, in the start topology, a relay server in the middle will be in charge of establishing peer connections and distributing streams among participants. For every client only one Peer connection independently of the increasing number of participants. Which is very scalable approach. All the burden and processing is left to the middle server. As an example, we propose kurento MCU, since it has many features. First of all, is an open source WebRTC media server. 

 It supports group communication, streaming, recording, augmented reality, transcoding, and media adaption good in case of changing network conditions[]. The inconvenient of this topology, that is not fault tolerant. Hence, this logic topology has a single point of failure, in case the media server is down. All communications are interrupted.
![untitled diagram 1](https://cloud.githubusercontent.com/assets/15377466/17848979/d8e26862-6856-11e6-855c-3bc1f2c862ee.png)

**Comment by pchainho** [comment]
Right, but in terms of the core framework and Hyperties, how can we support both these topologies?

For the meshed topology I've already provided some hints (the orchestrator idea has to be better analysed). But what about the Start topology?

Some ideas:

* nodejs runtime with a special protostub to connect to the media server to make it easier to work with other Media Server
* A single Hyperty supporting multiple connector data objects, one per participant)
* An orchestrator hyperty coordinating simpler two party Connectors one per participant
* A floor control Hyperty

**Comment by jboulmal** [comment]
These ideas can be source of inspiration for the start Topology as well.
The way I thing of it is the following :
- A single Conference Server Hyperty  running on `runtime nodejs`. This hyperty connects to the media server using custom protostub on one hand.
- On the other hand, it also supports multiple connector data objects, one per participant (as you said @pchainho ).

I'm afraid I haven't understood the floor control and the orchestrator concepts ?

**Comment by pchainho** [comment]
Floor Control is about controlling the sharing or resources among participants. BFCP is a standard protocol for Floor Control but as far as I know not many media servers support. Some references:

https://tools.ietf.org/html/rfc4376

https://www.ietf.org/rfc/rfc4582.txt

Regarding the Orchestrator Hyperty this is still something to be further elaborated and validated but the idea is to orchestrate the message flows among simple Connector Hyperties in order to manage multiparty calls.

**Comment by jboulmal** [comment]
first, thanks for the explanation.
The figure below provides a big picture of star topology, we have proposed. In this star topology, we have three main components, Runtime browser, Runtime NodeJS, and the Media Server. While, the messaging node is just relay point in reTHINK framework. Thus, it's transparent for the different communication messages.

![proposal architecture](https://cloud.githubusercontent.com/assets/15377466/18167951/93f4b6ba-7053-11e6-95b9-b1c41868e1a5.png)


- `Runtime browser` implementing Client conference hyperty silmilar to Hyperty connector, but adapted for conferencing purposes.
- `Runtime Node` loading and executing `Server conference hyperty`. This intermediary server is used for webRTC signaling between client conference hyperty and Kurento Media server. This `Server conference hyperty` will act as proxy between reTHINK framework and  kurento media server.  
Once the signaling is done, media streams start flowing directly between participants Runtime browsers through the media server.

Concerning the orchestrator hyperty, we think is good idea to have this feature on the `Server conference hyperty` running on the Runtime Node. In fact, this hyperty will orchestrate other clients' conference hyperties. In addition, this hyperty has the ability to observer several clients' connections data objects. Each clients conference hyperty will be associated to a connection data object(for which he's the owner). Still, this proposal implementation needs to be further elaborated with respective call flows.

**Comment by jboulmal** [comment]
Here is a higher and simplified level view of how this call flow might look like:

<p align="justify">This call flow involves Hyperty conference of Client A (we can call him initiator) running on runtime browser A, hyperty conference of client B, Message Node(just relay no processing), Kurento media server, and Hyperty conference server running on Runtime Node as signaling server relaying messages between them. </p> 
![call-flows](https://cloud.githubusercontent.com/assets/15377466/18199684/c1c76412-7101-11e6-9185-0997ce03e955.png)

The sequence diagram evolves through the following macro steps:   

1. The `Hyperty conference server` (signaling server) connects to messaging node associated with Runtime Node and registers its instance in it.  
2. The messaging node  registers the hyperty  and provides back hyperty url to the `Hyperty conference server`.  
3.  At this point the `Hyperty conference server` (signaling server) creates a signaling channel, up listening for any incoming message from client.  
4. `Hyperty client A` (initiator) queries the messaging node to register its instance.  
5. The Messaging node registers the hyperty and replies back giving it an hyperty url.   
6. `Hyperty client A` connects to the `Hyperty conference server` and joins the channel.  
7. The `Hyperty conference server` accepts/refuses the join request.  
8. If accepted, the `Hyperty client A` (creates connection data object) sends its sdp offer to kurento media server via the signaling server.  
9. Upon receipt of the SDP offer, the kurento media server creates room pipeline and generates an SDP answer to be sent back (via the signaling server)  to the remote client A.  
10. `Hyperty client A` sends its local stream directly to kurento media server.   
11. If `Hyperty Client B` wants to join(the joiner) the same room pipeline as client A, it mirrors the same  behavior of hyperty A from step 4) to 10).  
12. The `Hyperty conference server` connects the two streams on kurento media server.  
13. At this point media streams are exchanged between client A and Client B passing by Kurento media server in star topology.

**Comment by pchainho** [comment]
Some initial comments.

Conference Hyperty should be discoverable ie Client Hyperties can search for existing Conference servers before they interact with it.

Then conference rooms can be created on the demand and they should also be discoverable if needed.

The procedures would be similar to chat rooms and the conference object would also be a [communication data object](https://github.com/reTHINK-project/dev-service-framework/tree/develop/docs/datamodel/data-objects/communication) but with resources "audio", "video". 

The main difference, is that with chat room we have no "Hyperty" server, only peers (actually calling Hyperty Server doesn't sound good).

One idea would be to have in the conference runtime (Communicator ?), an Hyperty running on behalf of the user that owns the conference room, ie, the Communicator would be associated to the identity of the user that has created the conference room (to be analysed implications to IdM in the Nodejs runtime).

**Comment by jboulmal** [comment]
Thanks for the feedback @pchainho !
The figure below rapresents the `internal` architecture together with respective call flows of the Client conference hyperty runtning on runtime browser of user initiating the conf. This hyperty quite similar to  [connector hyperty](https://github.com/reTHINK-project/dev-hyperty/blob/master/docs/connector/connector-invite_001.png) but with an advance feature of handling WebRTC conferencing capabilities as well.  These call flows involve `Client Conference App`, `Client Conference Hyperty`, `Syncher` , and `Mesage Bus`.
![client conference hyperty](https://cloud.githubusercontent.com/assets/15377466/18248823/e9688bb0-737a-11e6-8e73-0ff589dc2d7d.png)

In the following step-by-step description: 

- First, the `Client Conference App` will issue a request message to the `Client conference Hyperty ` asking to join a specific `room`, given that it knows already the `roomId` and the `serverHypertyURL` or it may search for existing Conference servers before it interacts with them(as suggested by @pchainho ). Otherwise, it requests the creation of a new room. Besides, provisioning for options is possible. 
- The `Client Conference hyperty` will get the local description of the peer issuing the request message. 
- Next, the hyperty will ask the Syncher to create connection object schema, for which is ```reporter(owner)```. Simultaneously, it's an observer of the server room object (description will be provided about this Server side connection object) involved in the Connection object. 
- The Syncher sends create connection object request to the `Server Conference Hyperty` through the `Message Bus`.  
- Finally, once an OK piggybacked response message is received. The `Syncher` will adds some `incoming details`(SDP answer,etc.) from the server hyperty to the data connection object. Afterwards, it returns it to the `Client Hyperty`, That includes it in its local connection controller object in order to control client WebRTC connection parameters.  
### notice :
The server connection object is a special object, created and maintained by the server Hyperty upon incoming request from client hyperty to create new room. Thus, this object is related to a room. Besides, is created by the Hyperty server which means is the reporter (owner) of this connection object. This object will be destroyed when the last participants leaves the room.

**Comment by pchainho** [comment]
These specs should be provided [here](https://github.com/reTHINK-project/specs/blob/master/group-communication/readme.md)

**Comment by jboulmal** [comment]
Here some points from slack (channel #dev-runtime-nodejs) from @pchainho :

1. using [communication data object](https://github.com/reTHINK-project/dev-service-framework/tree/develop/docs/datamodel/data-objects/communication) since it's agnostic to runtime environment, but upgraded to support media resources.
2. The server hyperty instead of being a single hyperty. It's a combination of two hyperty types in running in runtime nodejs:
 - One encapsulating the media server that would be responsible to interact and manage resources in the media server to create, manage, remove rooms according to available capacity. This would be associated to the `identity` of the conference service provider.

 - A second Hyperty type that would be responsible to manage rooms on behalf of some customer. This would be associated to the `identity` of the conference service customer.
In this scenario, we have two identities associated to same runtime in nodejs.

3. Users managing identities in remote runtimes. i.e using runtime browsers to manage identities in remote runtime nodejs identity modules.

Thus, some questions arises here:
 - What would be the impact on authentication/association of  hyperties identity management ?
 -  What are the use cases (technical/business) associated to this implementation ?

**Comment by pchainho** [comment]
pls see https://github.com/reTHINK-project/specs/issues/2

**Comment by pchainho** [comment]
duplicated with https://github.com/reTHINK-project/specs/issues/2
