### ISSUE TITLE
Runtime Instance shared by more than one App eg in different Tabs

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#111]
To follow this discussion:

https://github.com/reTHINK-project/core-framework/issues/137

**Comment by antonroman** [comment]
To summarize, we should focus on three possible solutions to check which of them meets more reTHINK requirements.

1. **intertab communication using localStorage**: This solution has been discussed in reTHINK-project/core-framework#137 it could work but it has several drawbacks: reTHINKS iframes need to be loaded from the same domain (one of this iFrames wouldn't load the whole runtime but would interact with the runtime loaded in the other tab).

2.  **intertab communication using sharedWorker**: SharedWorkers are defined here: https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker They are supported both from Chrome and Firefox. The solution sound more natural than the localStorage-based. Maybe the runtime should have always a sharedWorker, if another sharedWorker is detected then it should communicate with it ti use its runtime instead of deploying the rest of files of the core-runtime. Any feedback is welcome. 

3. **intertab communication using channel messaging**: in the doc(https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging) it claims to be able to communicate two documents via a SharedWorker so it sounds as a higher abstraction layer to use sharedworkers but it seems that it should be possible to do what we need.   

Additionally, the solution should be easily adapted to Node.js runtime, but I understand that here the browser-runtime is more constrained.

@pchainho we can leave reTHINK-project/core-framework#137 to keep discussing the localStorage approach and discuss sharedWorkers and Channel API in this issue. 

The week after the review we can schedule a half an hour meeting to discuss pros and cons of the different options to start working on the most promising one.

**Comment by pchainho** [comment]
Thx @antonroman by resuming this discussion in such a well structured way.

From your analysis, option 2 (sharedWorker) seems more promising and I like the idea of always having a sharedWorker that would be detected before a new instance of the runtime is created.: Would it be possible to make some experimentation to validate this approach before we go further in the discussion?

If it works we could also analyse the usage of SharedWorks to implement Protostub / Hyperty sandboxes, thus sharing network connections among several Apps / Hyperties deployed in different tabs. Pls note this discussion has an impact on the decision about the implementation of the P2P Stub sandbox #103 .

Regarding the NodeJS, I understand there is a one to one relationship between NodeJS instances and App instances but perhaps I'm wrong.

**Comment by pchainho** [comment]
One issue we should clarify with SharedWorkers is about closing the tab where the runtime SharedWorker was first loaded: is the SharedWorker destroyed?

**Comment by pchainho** [comment]
duplicated with https://github.com/reTHINK-project/specs/issues/15
