### ISSUE TITLE
Persistence Manager is breaking with the amount of data being stored

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#119]
It seems Local Storage was designed for small amounts of data. Should we use indexeddb for runtime browser and something else for node runtime? 

We should give priority to this one

**Comment by jboulmal** [comment]
As far as runtime node is concerned, there are some modules [node-persist](https://www.npmjs.com/package/node-persist) that can be pluged into RuntimeFactory, this way the runtime-core remains agnostic. Otherwise, we detect the environment using runtimeUA and we adapt Persistence Manager accordingly.
These are just some inline suggestions.

**Comment by pchainho** [comment]
Exactlym that's the idea. Then I'll create two separated issues to address this bug, on in browser runtime, another in node runtime.

**Comment by dvilchez** [comment]
Since persistence is a external dependecy injected by RuntimeFactory and coupled to a particular implementation (nodejs or browser) we should move this  feature and this conversation to https://github.com/reTHINK-project/dev-runtime-browser/issues/58

**Comment by pchainho** [comment]
It seems we need to change the API: https://github.com/reTHINK-project/dev-runtime-browser/issues/58#issuecomment-255035349

@dvilchez could you propose something in order to minimum impact on current consumers of persistence manager API ?

Then I would like to hear the opinion of all persistence consumers including @Endebert , @AnaSLCaldeira, @jboulmal and @gamdias

**Comment by pchainho** [comment]
@dvilchez will try a sync API on top of indexedDB

**Comment by dvilchez** [comment]
I can’t find any way to expose the indexeddb calls as sync calls without making any change in the public API. I tried generators and async/await but both of them pollute the current API and there isn’t any way to do it in  a non busy-waiting way, as far as I know.

I guess we have to change the public API, my proposal is something like that:

persistenceManager.set('key', 'v1.0.0', {}).then(key => console.log(key)).catch(console.error)
persistenceManager.get('key').then(object => console.log(object.key)).catch(console.error)
persistenceManager.getVersion('key').then(version => console.log(version)).catch(console.error)
persistenceManager.delete('key').then(key => console.log(key)).catch(console.error)

what do you think @jboulmal   @AnaSLCaldeira  @Endebert  @vitormsilva  @gamdias?

**Comment by pchainho** [comment]
pls provide your feedback ASAP. This is urgent.

@dvilchez, in the meanwhile would it be possible for some period of time to keep both APIs available?

**Comment by jboulmal** [comment]
To be clear , `indexedDB API` is not supported in Node.js. Eventhough, there exist some modules that are outdated and less documented [indexeddb-js](https://github.com/metagriffin/indexeddb-js). Thus, we can't ensure they are reliable. However, we may thing of using [Redis.io](http://redis.io/) as local storage for Node. 
But, more likely it will be asynchronous calls, as the nature of Node. Beside, we think considerable effort is required to make synchronous I/O.

**Comment by pchainho** [comment]
@jboulmal  the new API is asynchronous

**Comment by gamdias** [comment]
I agree with the API proposed by @dvilchez.

I just have a question regarding the "version" field. It is supposed to be set by the component making use of the persistenceManager? That field is not very clear to me.

**Comment by dvilchez** [comment]
Storage manager proposal https://github.com/reTHINK-project/dev-runtime-browser/pull/59

**Comment by pchainho** [comment]
{Storage Manager is ready to be used](https://github.com/reTHINK-project/dev-runtime-browser/pull/59)

**Comment by Endebert** [comment]
The new api seems reasonable. It implies quite a few changes in RuntimeCatalogue, but I guess there is no way around this.

However, @dvilchez, this is a public API, please document your code accordingly. For example, it would be nice to know what happens if I do a `get()` but there is no match in the database. Will it return `undefined` as it did in the old API, or will an error be thrown?

Just want to make sure that you are not expecting a user of the StorageManager to do error handling.

**Comment by jboulmal** [comment]
Fortunatelly, this API seems [Dexie.js - A Minimalistic Wrapper for IndexedDB](https://github.com/dfahlander/Dexie.js) be also compatible with node. Still, some adaptations are needed in runtime nodejs.

**Comment by dvilchez** [comment]
Sorry @Endebert, what is "according documentation"? any example.

**Comment by Endebert** [comment]
@dvilchez I'm asking you to [document your code](http://usejsdoc.org/about-getting-started.html), especially if you know that other people will use it. I (the user) doesn't know how your backend works, when an error is thrown or not, what is allowed or not. You added this abstraction layer so you have to tell me what I can expect when using your code. A short description and notes about special use cases. For example:

* describe what happens if an entry with a certain key is already stored in the db and I store a new entry with the same key (for example, a newer version). (Will it override the old entry or add a new entry? Do I have to manage key uniqueness? If it adds a new entry (and this behaviour is intended), when I do a `get()` for that entry using its key, will I get the most recent entry or the first that was added? If it was the first that was added, how do I get the other entries?)
* describe what happens if I do a `get(key)` and `key` is not stored in the StorageManager ([like had to find out myself through testing](https://github.com/reTHINK-project/dev-runtime-browser/issues/61))
* describe what happens if I do a `getVersion(key)` and `key` is not stored in the StorageManager. Looking at the code I can already see that this will throw an error even though it shouldn't
* describe what happens if I try to delete a key that does not exist in the database
* describe what happens if I `set()` something without providing a version, and then do a `getVersion()` of it
* is it even allowed to `set()` something without a version?

Additionally, you should check for limitations and describe them in the documentation if there are any, like:

* are there limitations to the entries, like key or value size
* is there an upper max to the amount that can be stored in the StorageManager? Does the user have to handle this or does the StorageManager handles this? I.e. can the StorageManager break over time or can the user expect to have a stable StorageManager when it gets the instance?

All of these questions should be answered with the documentation. If you don't put it in your code, put it in a spec or something. Other runtimes (like the nodejs runtime) will also have to implement the StorageManager and we have to ensure that all implementations work the same way. You don't even declare that the StorageManager is asynchronous, or what type the return values are. Yes, currently we all read the issues and know about this, but what if there is someone new to the team, or someone else that wants to extend the runtime and use this feature? Or another runtime wants to implement StorageManager? How are those people supposed to know how your (reference) StorageManager behaves without testing every single scenario?

Just document your code. It doesn't take long, uncovers a lot of problems ahead of time, and makes everyone's life easier.

**Comment by dvilchez** [comment]
Hi @Endebert thank for your long explanation about code documentation. I was asking for it because when I implemented PersistenceManager no documentation was required, despite that I did tests to document the expected behaviour. In this case, I did the same, I can also add more tests to cover some side cases including what you have commented.

I like to write tests to document my APIs because tests are live documentation. But, if you think to write some specs is a good idea, I don't have any inconvenient in write it, only  give me some example to follow in order to keep the same scheme.

Thanks,

**Comment by pchainho** [comment]
@dvilchez pls take into account that storage manager was moved to service framework since nodejs also supports indexeddb with dexie.js

**Comment by pchainho** [comment]
here: https://github.com/reTHINK-project/dev-service-framework/tree/develop/src/storage-manager

@vitormsilva also made some changes in order to work with the Runtime Catalogue.

**Comment by jboulmal** [comment]
not natively @pchainho, still [polyfill](https://github.com/axemclion/IndexedDBShim) is needed with some issues:
```
adding promise to attach sourcePackage
{ MissingAPIError: indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using old Safari versions, make sure to include indexedDB polyfill.
    at new e (~/dev-runtime-nodejs/node_modules/service-framework/dist/StorageManager.js:28:6136)
    at Object.storageManager (~/dev-runtime-nodejs/dist/RuntimeFactory.js:87:12)
    at new e (~/dev-runtime-nodejs/node_modules/service-framework/dist/RuntimeCatalogue.js:30:21288)
    at Object.createRuntimeCatalogue (~/dev-runtime-nodejs/dist/RuntimeFactory.js:90:22)
  _e: 
   Error
       at getErrorWithStack (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:309:12)
       at new DexieError (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:420:19)
       at ~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1971:35
       at executePromiseTask ~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:930:9)
       at new Promise (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:723:5)
       at Dexie.open (~/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1957:45)
       at new e (~/dev-runtime-nodejs/node_modules/service-framework/dist/StorageManager.js:28:6136)
       at Object.storageManager (~/dev-runtime-nodejs/dist/RuntimeFactory.js:87:12)
       at new e (~/dev-runtime-nodejs/node_modules/service-framework/dist/RuntimeCatalogue.js:30:21288)
       at Object.createRuntimeCatalogue (~/dev-runtime-nodejs/dist/RuntimeFactory.js:90:22),
  name: 'MissingAPIError',
  message: 'indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using old Safari versions, make sure to include indexedDB polyfill.',
  inner: null }
```

**Comment by Endebert** [comment]
> I was asking for it because when I implemented PersistenceManager no documentation was required, despite that I did tests to document the expected behaviour.

And the lack of documentation bugged me back then, too, I just didn't say anything. Because I thought it would be added eventually.

> In this case, I did the same, I can also add more tests to cover some side cases including what you have commented.

Besides the case I had already [opened an issue on](https://github.com/reTHINK-project/dev-runtime-browser/issues/61), none of the cases I mentioned are covered by your test file.

> I like to write tests to document my APIs because tests are live documentation. 

Since when are tests equal to documentation? Do you really expect me to check your test files to see how your code works? Those tests are for _you_, not for me. I just want to know what I'm dealing with, is that too much to ask?

> But, if you think to write some specs is a good idea, I don't have any inconvenient in write it, only give me some example to follow in order to keep the same scheme.

I don't care if it is in another file or the code itself, just write some real documentation. This or something along those lines is what I expect from a documentation:
```
/**
 * Adds a new entry to the database for a given key, together with its version.
 * If an entry for the given key is already stored in the database, X happens.
 * @param {!string} key - key that can be used with {@link storageManager.get} to retrieve the value object
 * @param {!string} version - version descriptor for the given value
 * @param value - value stored in the database that is mapped to given key
 * @returns {Promise} result - Promise that will be fulfilled with Y if the entry was stored successfully,
 * otherwise it is rejected with error Z.
 */
set: (key, version, value) => {
	return db.objects.put({key: key, version: version, value: value})
}
```

**Comment by dvilchez** [comment]
Ok @Endebert, I totally disagree but I think we are not going to reach an agreement on this. In addition, I don't why but it seems this conversation is affecting you in some way so I will add some documentation as you require.

**Comment by pchainho** [comment]
done
