### ISSUE TITLE
Wrong Identity referenced in the ID Module

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-runtime-core#166]
The ID module seems to suppose that the identifier is an email format, which is usually the case, but not always (for example Microsoft proposes a phone number in its login form).
If I use the google authent I can see two cases.
* My account is a google email adress.
Thus I'm using john.doe@gmail.com to authenticate. The Idp referenced appears to be _gmail.com_ but it should be _accounts.google.com_
The hyperty references me as 
```
cn:"john.doe"
userURL: "user://gmail.com/john.doe"
username:"john.doe@gmail.com"
```
it should be
```
cn:"john.doe@gmail.com"
userURL: "user://accounts.google.com/john.doe@gmail.com"
username:"Whatever display name"
```
* My account is another email adress. For example I have a google account, but my user ID is a yahoo email address. I authenticate on google with john.doe@yahoo.fr
The hyperty references me as 
```
cn:"john.doe"
userURL: "user://yahoo.fr/john.doe"
username:"john.doe@yahoo.fr"
```
it should be
```
cn:"john.doe@yahoo.fr"
userURL: "user://accounts.google.com/john.doe@yahoo.fr"
username:"Whatever display name"
```

In the second case, my IdP is lost.

**Comment by tiagolb** [comment]
@sbecot Could you please give me more information regarding this issue?

I'm asking this because, in the first case I get a different result than the one described.
Using the email `john.doe@gmail.com` I get this:
```
cn:"john.doe"
userURL: "user://google.com/john.doe@gmail.com"
username:"john.doe@gmail.com"
```

Instead of this:
```
cn:"john.doe"
userURL: "user://gmail.com/john.doe"
username:"john.doe@gmail.com"
```

In the second case I don't really see a problem, because if you use the admin gui to setup your identities you have to select an identity provider before the popup appears.
So, if you choose the `google.com` identity provider then the value would be correct, and not `yahoo.fr` for the `john.doe@yahoo.fr` example.

**Comment by tiagolb** [comment]
I have performed some tests and I've come to the conclusion that this is functional and is performing without the described error above. If you are still getting this error please reopen the issue and provide an example for me to test and verify, so that I can fix it later on. 

This said, I'll close this issue.

**Comment by sbecot** [comment]
It may have been corrected, I have to test it with the last version, but if you want to see an example with the error above you can try https://call.rethink.orange-labs.fr/ .
Anyway, google.com is the name of the IdP proxy provided in the catalogue, but certainly not the IdP of google. The google IdP is "accounts.google.com", so it would at least more convient to name the IdP Proxy "Google" instead of "google.com".
