### ISSUE TITLE
"window" reference inside the identity module

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#171]
To have this [Runtime Sharing](https://github.com/reTHINK-project/dev-runtime-browser/issues/66) feature, we need to install the RuntimeUA inside a shared worker, until now, no problem.
The problem is when we install an hypery, inside the Identity Module we have a reference to the "window" method [here](https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/identity/IdentityModule.js#L439-L476), which is not supported by the shared worker or even workers.

Until now, we had not this problem, because RuntimeUA was installed inside an iframe.

So, this reference should be removed and should be replaced by a message sent to the runtime-browser.

**Comment by tiagolb** [comment]
I'll change this reference to the identity-gui in the runtime-browser.

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by tiagolb** [comment]
I have moved the `openPopup` funtion, where this "window" reference is present, to the identity-gui in `dev-runtime-browser`. But this is not enough since the runtime-core still needs to call this function when the hyperty-toolkit is in `dev` mode.

**Comment by tiagolb** [comment]
I've created issue #177 asking for this function to be supported in the hyperty-toolkit as a solution for this problem.

**Comment by tiagolb** [comment]
I've fixed this issue here:

- [dev-runtime-core#window-reference-fix](https://github.com/reTHINK-project/dev-runtime-core/tree/window-reference-fix)
- [dev-runtime-browser#window-reference-fix](https://github.com/reTHINK-project/dev-runtime-browser/tree/window-reference-fix)

This all works fine in my local machine, but the runtime-core branch I'm working on does not pass all the tests. I believe this has to do with changes made during the merging process with the develop branch.

@vitormsilva can you help me with this? I don't fully understand the errors that show up in the testing log [here](https://travis-ci.org/reTHINK-project/dev-runtime-core/builds/215579254).

**Comment by tiagolb** [comment]
This specific issue has been fixed, but there are still problems related other GUI references inside the shared worker. These problems are described here: [dev-runtime-browser#67](https://github.com/reTHINK-project/dev-runtime-browser/issues/67).

I'll close this issue now.
