### ISSUE TITLE
Graph Connector: reduce size

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#178]
Currently the Graph Connector is too big around ~3.5 M in dev mode. Pls reduce it as much as possible

**Comment by fbeierle** [comment]
We started working on this: https://github.com/reTHINK-project/dev-runtime-core/tree/issue178
We already could reduce the size by 1 M and we are looking if we can further reduce it.

**Comment by fbeierle** [comment]
We tried a few things but weren't successful in reducing the size further.

We had the idea if it would be possible to distribute the runtime in some gzipped format in order to reduce the size.

For now, I'll create a pull request and close this issue

@sgoendoer @SenanSharhan @vitormsilva @pchainho
