### ISSUE TITLE
Login popup issues

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#188]
When loading Group Chat Manager, if I take some time (1-2 sec) to login:

![image](https://cloud.githubusercontent.com/assets/3893553/25095300/16853bfc-2393-11e7-967d-fcae4b136947.png)

The same kind of problem when inviting a slack user for a Group Chat:

![image](https://cloud.githubusercontent.com/assets/3893553/25095846/537e90e2-2395-11e7-9b00-b1fe5f8f3548.png)

**Comment by tiagolb** [comment]
@pchainho Could you please check where that first `TypeError: Cannot read property 'profile' of undefined` appears? My code never tries to read a property named profile.

Also, I have tested commenting the code that validates the token expiration dates as to assess whether this code introduced the problem and it seems the same problem regarding the `profile` property still remains, which in turn cascades down to that `CallGeneratemethods` error.

Additionally, is it normal for that first line of the image to indicate "invalid_auth"?

Regarding the first problem. It seems the openPopup function is returning without having an answer. I don't really know why this happens. I'm taking a look at it now.

**Comment by tiagolb** [comment]
@pchainho the problem for this issue is related to the OpenPopup function being only accessible via the messageBus. I've changed the openPopup function back to the IDM as a test and it works normally. But once the messageBus is used we get a timeout and the messageBus responds before the openPopup function answers (it responds by replying the sent message) thus, since the response is incorrect, an error occurs. Should I open an issue with this messageBus problem?

**Comment by tiagolb** [comment]
This issue has been fixed in these pull requests:
https://github.com/reTHINK-project/dev-runtime-core/pull/189
https://github.com/reTHINK-project/dev-hyperty-toolkit/pull/46
