### ISSUE TITLE
Mutual Authentication error for Subscribes after resume

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#199]
When a subscription is performed after the Reporter is resumed at least once, the mutual authentication fails.

![image](https://cloud.githubusercontent.com/assets/3893553/25957303/e4fefe52-3665-11e7-8b64-cb878788dc1a.png)

Steps to replicate with Group Chat Manager:

1- create a group without adding any participant
2- restart runtime with Group Chat Manager
3- invite a new participant or a remote hyperty asks to join

**Comment by tiagolb** [comment]
What's happening is that during the mutual authentication process when inviting a new participant, some data that should exist is returning as `undefined`, probably because the registry is not prepared to save this data in the first place.

These are the two functions that should return correct values:
https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/registry/Registry.js#L225
https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/registry/Registry.js#L290

The doMutualAuthentication error happens only because these functions are returning `undefined`. Fixing that fixes this issue.

**Comment by tiagolb** [comment]
@BernardoMG is fixing the registry

**Comment by tiagolb** [comment]
Fixed on this pull request: https://github.com/reTHINK-project/dev-runtime-core/pull/200

I'm going to close this issue now.
