### ISSUE TITLE
Runtime Catalogue: persistence

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#40]
To use the generic "Persistence Manager" to persist catalogue data avoiding the need to download previously deployed resources from the Catalogue server

**Comment by Endebert** [comment]
So far I have only implemented use of the persistence manager in getSourceCodeFromDescriptor().

The problem with catalogue objects is that when storing them in the persistence manager, the class properties get lost, i.e. you store a HypertyDescriptor and you retrieve a generic Object. This means that after restoring, all get/set functions are lost, like hyperty.version, hyperty.objectName, etc.

So I would have to create a function that takes the private attributes of the generic object (hyperty._version, hyperty._objectName, etc.) and create a Descriptor based on them. I doubt we want this, because that means I do specific implementation for things that should be abstracted from me.

I'm currently looking into ways of not losing the class when storing in persistence manager, or convert the generic object to the desired descriptor class instance.

**Comment by Endebert** [comment]
persistenceManager usage implemented for get***Descriptor() functions and getSourceCodeFromDescriptor().
