### ISSUE TITLE
Core Runtime deployment from the catalogue

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#66]
So far, the the Core Runtime is downloaded and deployed with the App.

To close phase 1 we have to separate the App deployment from the runtime core deployment by downloading it via the Runtime Catalogue.

**Comment by pchainho** [comment]
to be moved to dev service framework

**Comment by vitormsilva** [comment]
Hi @Endebert,

With the propose of installing the runtime-core from the catalogue, you will need to pass the [runtime-catalogue](https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.4/src/runtime/RuntimeCatalogue.js) to dev-service-framework.

I just passed the RuntimeCatalogue-Local to dev-service-framework.

What do you think?

**Comment by Endebert** [comment]
I just took a look at it, looks simple enough. I will move and adapt the code on friday.

@Trikolon If you have time could you please move the changes you did to the master branch (regarding the version tag) and make sure they are in the dev branch? Otherwise I will do it on friday.

**Comment by Endebert** [comment]
I have a question regarding the persistence manager. Can that be moved to dev-service-framework, too, or do I have to remove my implementation of it?

**Comment by Endebert** [comment]
Ok I have moved RuntimeCatalogue and PersistenceManager to dev-service-framework and adapted RuntimeCatalogue to reflect the changes in making http requests.

@vitormsilva please have a look at my commits, especially https://github.com/reTHINK-project/dev-service-framework/commit/5579613f69b54a08b1031c37e8f20da09355e016. I copied @Trikolon's changes from the master branch to the develop branch, so you will have to update RuntimeCatalogue-Local because the version attribute is now mandatory and needs to be provided when constructing a descriptor.

**Comment by vitormsilva** [comment]
This was moved to dev-service-framework, since don't have any new comments, i think we can close this;
