### ISSUE TITLE
Runtime Catalogue: handle IDP Proxy fallback

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#83]
When IDP Proxy is not hosted in the Domain Catalogue it should try the Runtime Catalogue.

**Comment by pchainho** [comment]
Notify @Endebert when ready

**Comment by vitormsilva** [comment]
@pchainho and @Endebert,

I did some modification to the runtimeCatalogue-Local to avoid two separated files with the same function but a with different code.

So, I extend the RuntimeCatalogue-Local from RuntimeCatalogue, and override the getDescriptor method to handle with the "local catalogue" and I did some fixes to the RuntimeCatalogue to support the current implementations, like IdpProxy fallback.

@Endebert, if you want to take a look at the code and if you see something are not right, let me know.
Thanks

**Comment by Endebert** [comment]
@vitormsilva Thanks for the notification.

I looked into the current state of the RuntimeCatalogue and I have some issues with it.

1. I take issue with how you extended `_createDataSchema`. Having a different return types in certain cases is bad coding and should be avoided if possible. Either the function returns a Promise, or it doesn't. 
Despite that, I would argue that retrieving the `sourcePackage` using the `sourcePackageURL` should not happen as part of the `_createDataSchema` function. Instead, the check should be performed outside of the function. Splitting up descriptor and sourcePackage was done for a reason, and your implementation defeats the whole purpose of it.
If it has to be done automatically (of which I disapprove of), put the sourcePackage retrieval into getDescriptor, so it works for all descriptor types. But I'd much prefer a new function that can be chained to the `getDescriptor` promise.

2. The url parsing you added to `getStubDescriptor` and `getIdpProxyDescriptor` should also be done outside of those functions. I'd prefer it if those adaptions would be outside of RuntimeCatalogue completely, but if it has to be in it, at least put it into `getDescriptor` to avoid having this duplicate code in every `get***Descriptor` function.

**Comment by vitormsilva** [comment]
@Endebert,

> I take issue with how you extended _createDataSchema. Having a different return types in certain cases is bad coding and should be avoided if possible. Either the function returns a Promise, or it doesn't. 

The return type is always a promise as you can see in screenshot and should be always;
![screenshot from 2016-05-27 09-58-13](https://cloud.githubusercontent.com/assets/10596749/15603253/934f8bd0-23f1-11e6-90b7-738b72082256.png)

> Despite that, I would argue that retrieving the sourcePackage using the sourcePackageURL should not happen as part of the _createDataSchema function. Instead, the check should be performed outside of the function. Splitting up descriptor and sourcePackage was done for a reason, and your implementation defeats the whole purpose of it.

Yes, you are right, but for some reason you don't use the method getSourcePackageFromURL, and if the getHypertyDescriptor had and sourcePackageURL will fail.
The descriptor should be returned complete, so, the request to get the source package from a URL should be done inside the catalogue not outside. Yes, could be done in the getDescriptor method. 
I did that for the getIdpProxyDescriptor because is an important method and without it, all the project doesn't work.
In my opinion, you should adapt all the code to handle with that presuppose and you can do in your own way.


> The url parsing you added to getStubDescriptor and getIdpProxyDescriptor should also be done outside of those functions. I'd prefer it if those adaptions would be outside of RuntimeCatalogue completely, but if it has to be in it, at least put it into getDescriptor to avoid having this duplicate code in every get***Descriptor function.

This is methods with specific behaviours, is not to duplicate this code in every get**Descriptor. 
getIdpProxyDescriptor - have a fallback to handle the first request to the "google.com" for example
getStubDescriptor -  have that condition, because the hyperty URL have the catalogue in the domain, but is removed inside the runtime-core, to handle with the registry, msg-node and other components, and need to be added to get the StubDescriptor from the catalogue.


You could perform an optimization, and should be done, but you need have in consideration the changes done; 
All the code it's working now.

If you don't agree with something I said, let me know for we discuss and reach an agreement.

**Comment by Endebert** [comment]
> The return type is always a promise as you can see in screenshot and should be always;

No, it is not. Look at this code snippet from `_createDataSchema`:

```
let sourcePackage = rawSchema["sourcePackage"];
if (sourcePackage) {
    console.log("dataSchema has sourcePackage:", sourcePackage);
    dataSchema.sourcePackage = _this._createSourcePackage(_this, sourcePackage);

    try {
      dataSchema.sourcePackage.sourceCode = JSON.parse(dataSchema.sourcePackage.sourceCode);
    } catch (e) {
      console.log('DataSchema Source code is already parsed');
    }

    return dataSchema;

} else {
  console.log('4. getSourcePackageFromURL: ', rawSchema.sourcePackageURL);

  return new Promise(function(resolve, reject) {

    _this.getSourcePackageFromURL(rawSchema.sourcePackageURL).then(function(sourcePackage) {
      console.log('5. result of getSourcePackageFromURL', sourcePackage);
      dataSchema.sourcePackage = sourcePackage;
      resolve(dataSchema);
    }).catch(function(reason) {
      console.log('Error getting the sourcePackageURL ', reason);
      reject(reason);
    });
  })
}
```

Therefore, if sourcePackage is already provided, it would return the dataSchema directly. Otherwise, it returns a Promise. It even states in the function description that the return type of `_createDataSchema` is DataObjectSchema, which you completely disregard. The fact that sourcePackage is never part of the descriptor is based on my implementation of the Catalogue Broker & Database, and might change in the future.

> Yes, you are right, but for some reason you don't use the method getSourcePackageFromURL, and if the getHypertyDescriptor had and sourcePackageURL will fail.
The descriptor should be returned complete, so, the request to get the source package from a URL should be done inside the catalogue not outside. Yes, could be done in the getDescriptor method. 
I did that for the getIdpProxyDescriptor because is an important method and without it, all the project doesn't work.
In my opinion, you should adapt all the code to handle with that presuppose and you can do in your own way.

No, my implementation does not intend to return the complete descriptor. If so, why even have this split of descriptor and sourcePackage? It only returns the descriptor part (unless sourcePackage is directly defined in the descriptor), this is useful for example if you only want to display information about the hyperty, without loading the sourcePackage. Otherwise I would implement this on the broker side.

getSourcePackageFromURL is simply a convenience function for other developers that I implemented.

As mentioned in my previous comment, If you want you can add an optional boolean flag to getDescriptor and extend it to retrieve the sourcePackage and attach it to the descriptor object, if the flag is set.

> This is methods with specific behaviours, is not to duplicate this code in every get**Descriptor. 
getIdpProxyDescriptor - have a fallback to handle the first request to the "google.com" for example
getStubDescriptor - have that condition, because the hyperty URL have the catalogue in the domain, but is removed inside the runtime-core, to handle with the registry, msg-node and other components, and need to be added to get the StubDescriptor from the catalogue.

Why does this parsing need to be done in RuntimeCatalogue at all, and not outside of it? My implementation expects simple HTTP URLs to retrieve JSON objects from and create the objects you need based on them, so in my opinion, the url you provide when calling getDescriptor() should already be adapted in the way you do it inside of the functions.

Also, in the idpproxy part you have `let originDividedURL = divideURL(_this.runtimeURL);` Where does runtimeURL come from? It is not set anywhere in my implementation.

> You could perform an optimization, and should be done, but you need have in consideration the changes done; 

Sorry, I don't understand.

> All the code it's working now.

It is only working under specific circumstances, e.g. only as long as sourcePackage is not part of the descriptor, or if _createDataSchema is wrapped in a Promise. If we do it properly from the get-go, we won't have to refine the code constantly to adapt to edge cases, especially if they are easily predictable.

I put a lot of effort into the code, structuring and documenting it to the best of my abilities, and all I expect from you is to treat it with the same care I did.

**Comment by vitormsilva** [comment]
I understand your point of view, and yes.. you are right, but I try to do my best too;

The code in the catalogue wasn't our responsibility (ptinovacão),
and we needed something quick to work and testing. So, you are free to change all the code.

The question of idpproxy fallback, is only http request, nothing more,
the parsing, yes, could be done in the runtime.

**Comment by pchainho** [comment]
This feature has been implemented and released.
